const fs = require('fs');
const path = require('path');
const axios = require('axios');
require('dotenv').config();

const HISTORY_FILE = path.join(__dirname, '..', 'data', 'topics_history.json');

// Built-in curated high-retention Factition scripts for instant offline/free generation
const CURATED_FACTITION_TOPICS = [
  {
    topic: "The Glass Rain Planet (HD 189733b)",
    searchQuery: "deep space galaxy planets stars",
    title: "The Terrifying Planet Where It Rains Glass Sideways! 🌧️🪐 #shorts",
    script: "Did you know there is a planet where it literally rains molten glass sideways? 64 light-years away sits HD 189733b, a giant alien world with deadly cobalt-blue clouds. But don't let its peaceful blue color fool you. The atmosphere reaches a scorching 1,700 degrees Fahrenheit, melting silicate particles into liquid glass. Worse yet, winds howl at over 5,400 miles per hour, seven times the speed of sound! If you stepped onto this planet, you would instantly be shredded by billions of flying glass shards. Would you dare visit deep space? Drop a comment below!"
  },
  {
    topic: "The Sound of Saturn's Rings",
    searchQuery: "saturn rings space cosmos dark universe",
    title: "NASA Recorded What Saturn Sounds Like and It's Terrifying! 🪐🔊 #shorts",
    script: "Astronomers pointed NASA's Cassini spacecraft directly at Saturn's rings, and what they recorded will give you chills. In the dead silence of space, Saturn emits an eerie, ghost-like howling sound. These intense radio emissions are generated by charged particles swirling through the planet's magnetic field. When scientists translated these waves into human audio, it sounded like a haunted choir drifting through the cosmic abyss. Could you sleep at night listening to this planet? Tell me in the comments!"
  },
  {
    topic: "The Deepest Hole on Earth (Kola Superdeep)",
    searchQuery: "underground cave dark tunnel geology magma",
    title: "What Scientists Heard Inside the Deepest Hole on Earth! 🕳️😱 #shorts",
    script: "Deep inside the Russian Arctic lies the deepest artificial point on Earth: the Kola Superdeep Borehole. Drilling went down an astonishing 40,000 feet into the Earth's crust. But as miners drilled deeper, the temperature skyrocketed to 356 degrees Fahrenheit, melting their drill bits into sludge. When acoustic sensors were lowered into the pitch-black abyss, they recorded terrifying screeching sounds that sounded like human screams. Scientists sealed the borehole with a heavy steel lid and abandoned the site forever. What do you think is really down there? Comment below!"
  },
  {
    topic: "The Immortal Creature (Turritopsis Dohrnii)",
    searchQuery: "ocean deep underwater jellyfish mysterious creatures",
    title: "Scientists Discovered a Creature That Literally Lives Forever! 🌊🪼 #shorts",
    script: "Did you know there is a living creature on Earth that can cheat death forever? Deep in the Mediterranean Sea lives Turritopsis Dohrnii, famously known as the immortal jellyfish. Whenever this tiny creature is injured, starves, or ages, its body undergoes a biological miracle called transdifferentiation. Its adult cells transform back into youthful stem cells, transforming it back into a baby polyp! It can repeat this cycle an infinite number of times, making it biologically immortal. If humans could unlock this genetic secret, would you want to live forever? Comment your thoughts below!"
  },
  {
    topic: "The Void of Boötes (Cosmic Nothingness)",
    searchQuery: "space dark void galaxy stars cosmic mystery",
    title: "The Most Terrifyingly Empty Place in the Entire Universe! 🌌😨 #shorts",
    script: "Imagine traveling across space and finding absolutely nothing for 330 million light-years. This is the Boötes Void, a terrifying chasm in the universe so immense it should contain over 10,000 galaxies. Instead, astronomers have found only a tiny handful. If our Milky Way galaxy were inside the Boötes Void, we wouldn't have known other galaxies existed until the late 1960s. Scientists still cannot explain why this gigantic area of the cosmos is almost completely devoid of matter. What created this massive cosmic graveyard? Comment below!"
  }
];

// Helper to load topic history
function getTopicHistory() {
  if (!fs.existsSync(HISTORY_FILE)) {
    return [];
  }
  try {
    const data = JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf-8'));
    return Array.isArray(data) ? data : [];
  } catch (e) {
    return [];
  }
}

// Helper to save new topic into history
function saveTopicHistory(topic) {
  const history = getTopicHistory();
  history.push({
    topic: topic,
    timestamp: new Date().toISOString()
  });

  // Keep only topics from the last 30 days
  const thirtyDaysAgo = Date.now() - (30 * 24 * 60 * 60 * 1000);
  const filtered = history.filter(item => new Date(item.timestamp).getTime() > thirtyDaysAgo);

  fs.writeFileSync(HISTORY_FILE, JSON.stringify(filtered, null, 2), 'utf-8');
}

// Check if topic was covered in last 30 days
function isTopicRecent(topic) {
  const history = getTopicHistory();
  const thirtyDaysAgo = Date.now() - (30 * 24 * 60 * 60 * 1000);
  return history.some(item => 
    item.topic.toLowerCase() === topic.toLowerCase() && 
    new Date(item.timestamp).getTime() > thirtyDaysAgo
  );
}

/**
 * Get next high-retention Factition script
 */
async function generateFactitionScript(customTopic = null) {
  // If user provided a specific topic, use it or look up in curated list
  if (customTopic) {
    const found = CURATED_FACTITION_TOPICS.find(t => t.topic.toLowerCase().includes(customTopic.toLowerCase()));
    if (found) {
      saveTopicHistory(found.topic);
      return found;
    }
  }

  // Find a topic from curated list that hasn't been used in the last 30 days
  for (const item of CURATED_FACTITION_TOPICS) {
    if (!isTopicRecent(item.topic)) {
      saveTopicHistory(item.topic);
      return item;
    }
  }

  // If all were used, reset cycle and pick the oldest
  const picked = CURATED_FACTITION_TOPICS[0];
  saveTopicHistory(picked.topic);
  return picked;
}

module.exports = {
  generateFactitionScript,
  getTopicHistory,
  saveTopicHistory
};
